version: '2'
services:
  upwork-extractor:
    build:
      context: .
      dockerfile: data-extractor/Dockerfile
    container_name: "upwork-extractor"
    ports:
      - 8080:8080
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb/upwork
      - SERVER_PORT=8080
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    volumes:
      - ./data/:/data/db
    command: mongod --smallfiles --logpath=/dev/null
