spring:
  application:
    name: telegram-manager
  data:
    mongodb:
      database: upwork
      uri: mongodb://localhost
  cache:
    type: hazelcast
  hazelcast:
    config: classpath:hazelcast.xml
bot:
  name: "GregSolutionsJobListenerBot"
  token: "843031210:AAHqeOjMDaHCnxQI3fMicw_-9VKcZHKi7Dc"

scheduler.job: "0/3 * * ? * *"